//THIS FILE TO ESTABLISH A CONNECTION WITH THE DB
const { connect, connection } = require('mongoose');

//CONNECTING CODE



//EXPORT IT
module.exports = connection;

//DIFFERENT FILES FOR CREATING THE ROUTES AND CONTROLLING THE ROUTES? 
//CONTROLLER.JS VS ROUTES.JS